#ifndef PDW_OUTPUT_ROUTES_H
#define PDW_OUTPUT_ROUTES_H

// Per-directory-rule delivery choices. A selected route is still gated by the
// corresponding global output setting; these bits never enable a destination.
enum PDW_OUTPUT_ROUTE
{
	PDW_OUTPUT_ROUTE_EMAIL = 1u << 0,
	PDW_OUTPUT_ROUTE_APPRISE = 1u << 1,
	PDW_OUTPUT_ROUTE_PUBLISHING = 1u << 2,
	PDW_OUTPUT_ROUTE_MQTT = 1u << 3,
	PDW_OUTPUT_ROUTE_SQLITE = 1u << 4,
	PDW_OUTPUT_ROUTE_MYSQL_ODBC = 1u << 5,
	PDW_OUTPUT_ROUTE_TELNET = 1u << 6,
	PDW_OUTPUT_ROUTE_WINDOWS = 1u << 7
};

const unsigned int PDW_OUTPUT_ROUTE_ALL =
	PDW_OUTPUT_ROUTE_EMAIL | PDW_OUTPUT_ROUTE_APPRISE |
	PDW_OUTPUT_ROUTE_PUBLISHING | PDW_OUTPUT_ROUTE_MQTT |
	PDW_OUTPUT_ROUTE_SQLITE | PDW_OUTPUT_ROUTE_MYSQL_ODBC |
	PDW_OUTPUT_ROUTE_TELNET | PDW_OUTPUT_ROUTE_WINDOWS;

enum PDW_AGENCY_LABEL_POSITION
{
	PDW_AGENCY_LABEL_HIDDEN = 0,
	PDW_AGENCY_LABEL_BEFORE = 1,
	PDW_AGENCY_LABEL_AFTER = 2
};

#endif
