#define IDC_STATIC             -1

#define IDD_ICON                    97
#define PDWICON                     98
#define PDWMENU                     99
#define PDWACCEL                   100

#define ABOUTDLGBOX                101
#define LOGFILEDLGBOX              102
#define SETUPDLGBOX                103
#define OPTIONSDLGBOX              104
#define GENERALOPTIONSDLGBOX       105
#define COLORSDLGBOX               106
#define SCROLLDLGBOX               107
#define SYSTEMTRAYDLGBOX           110
#define FILTERDLGBOX               111
#define FILTEREDITDLGBOX           112
#define FILTEROPTIONSDLGBOX        113
#define FILTERFINDDLGBOX           114
#define FILTERCHECKDUPLICATEDLGBOX 115
#define MONSTATDLGBOX              116
#define CUSTOM_AUDIO_DLG           117
#define DEBUGDLGBOX                118
#define ACARS_COLORSDLGBOX         119
#define MOBITEX_COLORSDLGBOX       120
#define ERMES_COLORSDLGBOX         121
#define CLEARSCREENDLGBOX          123
#define MAIL_DLGBOX                124
#define SCREENOPTIONSDLGBOX        125
#define FTP_DLGBOX                 126
#define APPRISE_DLGBOX             127
#define SIGNAL_SOURCE_DLGBOX       128
#define PUBLISHING_DLGBOX          129
#define DATA_OUTPUTS_DLGBOX        130
#define OUTPUT_HEALTH_DLGBOX       131
#define CONFIG_BACKUP_DLGBOX       132
#define CONFIG_BACKUP_PASSWORD_DLGBOX 133
#define CAPCODE_DIRECTORY_DLGBOX 134
#define MESSAGE_HISTORY_DLGBOX 135
#define LIVE_DASHBOARD_DLGBOX 136
#define MULTI_CHANNEL_DLGBOX 137

#define IDM_LOGFILE                201
#define IDM_EXIT                   202

#define IDM_COPY_SELECTION         210
#define IDM_COPY_UPPER             211
#define IDM_COPY_LOWER             212
#define IDM_COPY_SAVE              213
#define IDM_COPY_PRINT             214

#define IDM_INTERFACE              220
#define IDM_VOLUME                 221

#define IDM_OPTIONS                230
#define IDM_GENERAL                231
#define IDM_MAIL                   232
#define IDM_FTP                    233
#define IDM_APPRISE                234
#define IDM_SETTINGS               235
#define IDM_THEME_SYSTEM           236
#define IDM_THEME_LIGHT            237
#define IDM_THEME_DARK             238
#define IDM_SIGNAL_SOURCES         239
#define IDM_PUBLISHING             246
#define IDM_DATA_OUTPUTS           247
#define IDM_OUTPUT_HEALTH          248
#define IDM_CONFIG_BACKUP          249

#define IDM_FILTERS                240
#define IDM_FILTEROPTIONS          241
#define IDM_RELOAD                 242
#define IDM_RESET_HITCOUNTERS      243
#define IDM_FILTERFILE_EN          244
#define IDM_FILTERCOMMANDFILE      245

#define IDM_CLEARDISPLAY           250
#define IDM_COLOR                  251
#define IDM_FONT                   252
#define IDM_SCREENOPTIONS          253
#define IDM_SCROLLBACK             254
#define IDM_SYSTEMTRAY             255

#define IDM_POCSAGFLEX             260
#define IDM_ACARS                  261
#define IDM_MOBITEX                262
#define IDM_ERMES                  263
#define IDM_MONSTAT                264

#define IDM_HELP                   280
#define IDM_ABOUT                  281
#define IDM_SETTINGS_SIGNAL_PAGE   282
#define IDM_KEYBOARD_SHORTCUTS     283

#define IDM_DEBUG                  290
#define IDM_PANE_SWITCH            291

#define IDM_PLAYBACK               295
#define IDM_RECORD                 296
#define IDM_AUTORECORD             297
#define IDM_CAPCODE_DIRECTORY      298
#define IDM_MESSAGE_HISTORY        299
#define IDM_LIVE_DASHBOARD         300
#define IDM_MULTI_CHANNEL          301

#define IDS_APPNAME                591
#define IDS_SHORT_APPNAME          592
#define IDS_API_FAILED_MSG         593

#define IDC_ERR                    600
#define IDC_OKCANCEL               601
#define IDC_VERSION                602

#define IDC_LOGFILEEN              610
#define IDC_LOGFILE                611
#define IDC_LOGFILEDATE            612
#define IDC_LOGBROWSE              613
#define IDC_LOGCOLUMN              620 // 621 to 627 are reserved

#define IDC_COMENABLE              630
#define IDC_COMPORT                631
#define IDC_COMADDR                632
#define IDC_COMIRQ                 633
#define IDC_COMSLICER              634
#define IDC_COMRS232               635
#define IDC_RS232MODE              636
#define IDC_LEVEL                  637
#define IDC_AUDIOENABLE            638
#define IDC_AUDIOSAMPLERATE        639
#define IDC_AUDIOCONFIG            640
#define IDC_AUDIOCUSTOM            641
#define IDC_AUDIODEVICES           642

#define IDC_CONFIRMEXIT            650
#define IDC_DECODEPOCSAG           651
#define IDC_DECODEFLEX             652
#define IDC_POCSAG_512             653
#define IDC_POCSAG_1200            654
#define IDC_POCSAG_2400            655
#define IDC_POCSAG_FNU             656
#define IDC_POCSAG_BOTH            657
#define IDC_FLEX_1600              659
#define IDC_FLEX_3200              660
#define IDC_FLEX_6400              661
#define IDC_ACARS_PC_YES           662
#define IDC_ACARS_PC_NO            663
#define IDC_MB_USEFRSYNC           664
#define IDC_MB_FRSYNC              665
#define IDC_MB_BITSYNC             666
#define IDC_MB_BITRATE             667
#define IDC_MB_RAMNET              668
#define IDC_MB_MIN_MSG             669
#define IDC_MB_BITSCRAMBLER        670
#define IDC_MB_SHOWMPAK            671
#define IDC_MB_SHOWTEXT            672
#define IDC_MB_SHOWHPDATA          673
#define IDC_MB_SHOWDATA            674
#define IDC_MB_SHOWHPID            675
#define IDC_MB_SHOWSWEEP           676
#define IDC_MB_VERBOSE             677
#define IDC_SHOWINSTR              678
#define IDC_CONVERT_SI             679
#define IDC_SHOW_CFS               680
#define IDC_GENERALOPTIONS         681
#define IDC_BLOCKDUPLICATE         682
#define IDC_BLOCKDUPOPTION         683
#define IDC_BLOCKDUPTIMER          684
#define IDC_BLOCKEDTXT             685
#define IDC_WORDWRAP               686
#define IDC_LOGFILEPATH            687
#define IDC_LOGFILEPATHBROWSE      688
#define IDC_LOGFILEPATHDEFAULT     689
#define IDC_LOGFILEPATHTEXT        690
#define IDC_LINEFEEDS              691
#define IDC_FLEXTIME               692
#define IDC_SHOW_REJECTBLOCKED     693
#define IDC_SEP_SCREEN             694
#define IDC_SEP_LOGFILE            695
#define IDC_SEP_FILTERFILE         696
#define IDC_SEP_SEPFILES           697
#define IDC_SEP_MESSAGE            698
#define IDC_SEP_MSGTIMEDATE        699
#define IDC_DATEFORMAT             700
#define IDC_MONTHNUMBER            701
#define IDC_MONTHNUMBER2           702
#define IDC_SEPARATOR              703

#define IDC_COLORBACKGND           710
#define IDC_COLORCAPCODE           711
#define IDC_COLORFLEXPHASE         712
#define IDC_COLORTIMESTAMP         713
#define IDC_COLORBITERRORS         714
#define IDC_COLORNUMERIC           715
#define IDC_COLORALPHANUM          716
#define IDC_COLORFLEXBIN           717
#define IDC_COLORFILTMATCH         718
#define IDC_COLORDEFAULT           719
#define IDC_COLORWIN               720
#define IDC_COLORFILTERLABEL       721
#define IDC_COLORINSTRUCTIONS      722

#define IDC_AC_COLORMSGNO          730
#define IDC_AC_COLORTIMESTAMP      731
#define IDC_AC_COLORDBI            732
#define IDC_AC_COLORMODE           733
#define IDC_AC_COLORTAGS           734
#define IDC_AC_COLORMSG            735
#define IDC_AC_COLORBACKGND        736
#define IDC_AC_COLORBITERRORS      737
#define IDC_AC_COLORFILTMATCH      738
#define IDC_AC_COLORDEFAULT        739
#define IDC_AC_COLORWIN            740
#define IDC_AC_COLORFILTERLABEL    741

#define IDC_MB_COLORMAN            750
#define IDC_MB_COLORTIMESTAMP      751
#define IDC_MB_COLORSENDER         752
#define IDC_MB_COLORTYPE           753
#define IDC_MB_COLORMESSAGE        754
#define IDC_MB_COLORMISC           755
#define IDC_MB_COLORBACKGND        756
#define IDC_MB_COLORFILTMATCH      757
#define IDC_MB_COLORBITERRORS      758
#define IDC_MB_COLORDEFAULT        759
#define IDC_MB_COLORWIN            760
#define IDC_MB_COLORFILTERLABEL    761

#define IDC_EM_COLORCAPCODE        770
#define IDC_EM_COLORTIMESTAMP      771
#define IDC_EM_COLORFUNCTION       772
#define IDC_EM_COLORBITERRORS      773
#define IDC_EM_COLORNUMERIC        774
#define IDC_EM_COLORALPHANUM       775
#define IDC_EM_COLORBACKGND        776
#define IDC_EM_COLORFILTMATCH      777
#define IDC_EM_COLORTRANSPARENT    778
#define IDC_EM_COLORFILTERLABEL    779
#define IDC_EM_COLORWIN            780
#define IDC_EM_COLORDEFAULT        781

#define IDC_SCREEN_COLUMN          800 // 801 to 807 are reserved

#define IDC_FLEXGROUPMODE          810
#define IDC_FGM_LOGGING            811
#define IDC_FGM_COMBINE            812
#define IDC_FGM_HIDEGROUPCODES     813
#define IDC_FLEX_REASSEMBLY        814

#define IDC_SCROLLPANE1            890
#define IDC_SCROLLPANE2            891
#define IDC_SCROLLSPEED            892
#define IDC_PERCENTPANE1           893
#define IDC_PERCENTPANE2           894

#define IDC_FILTERS                900
#define IDC_FILTERRELOAD           901
#define IDC_FILTERADD              902
#define IDC_FILTEREDIT             903
#define IDC_FILTERDEL              904
#define IDC_FILTEROPTIONS          905
#define IDC_FILTER_CHECK_RESULTS   906

#define IDC_FILTERFILEEN           910
#define IDC_FILTERBROWSE           911
#define IDC_FILTERFILE             912
#define IDC_FILTERFILEDATE         913
#define IDC_FILTERTONE             914
#define IDC_FILTERNUMERIC          915
#define IDC_FILTERBINARYHEX        916
#define IDC_FILTERBEEP             917
#define IDC_FILTERDEFTYPE          918
#define IDC_FILTERWINDOWONLY       919
#define IDC_FILTERSCOLORS          920
#define IDC_FILTERSEXTRA           921

#define IDC_FILTERLOGCOLUMN        930 // 931 to 937 are reserved

#define IDC_LABELLOG               940
#define IDC_LABELSEPFILES          941
#define IDC_LABELNEWLINE           942

#define IDC_FILTERCMDBROWSE        950
#define IDC_FILTERCMDFILE          951
#define IDC_FILTERCMDARGS          952
#define IDC_FILTERCMDEN            953
#define IDC_FILTERHITS             954
#define IDC_FILTERLASTHIT          955
#define IDC_FILTERRESET            956
#define IDC_HITCOUNTER_BOX         957
#define IDC_DONTCHANGE             958

#define IDC_FILTERTYPE             960
#define IDC_FILTERREJECT           961
#define IDC_FILTERCAPCODE          962
#define IDC_FILTERFNU              963
#define IDC_FILTERLABEL            964
#define IDC_FILTERLABELEN          965
#define IDC_FILTER_MONITOR_ONLY    966
#define IDC_FILTERTEXT             967
#define IDC_FILTERCMD              968
#define IDC_FILTERAUDIO            969
#define IDC_FILTERLABELCOLOR       970
#define IDC_FILTERMATCHEXACT       971
#define IDC_FILTERSMTP             972
#define IDC_FILTERRXTXMAN          973
#define IDC_FILTEREDITHELP         974

#define IDC_FILTER_PREVIOUS        976
#define IDC_FILTER_APPLY           977
#define IDC_FILTER_NEXT            978

#define IDC_FILTERFIND             980
#define IDC_FILTERFIND_CASE        981
#define IDC_FILTERFIND_HITS        982
#define IDC_FILTERFIND_DUPLICATE   983
#define IDC_FILTERDUP_PCT          984
#define IDC_PROGRESS1              985

#define IDC_SEPFILTERFILEEN        990
#define IDC_SEPFILTERFILE1         991
#define IDC_SEPFILTERFILE2         992
#define IDC_SEPFILTERFILE3         993
#define IDC_SEPFILTERFILEBROWSE1   994
#define IDC_SEPFILTERFILEBROWSE2   995
#define IDC_SEPFILTERFILEBROWSE3   996
#define IDC_SEPFILTERBOX           997

#define IDC_SYSTEMTRAY            1000
#define IDC_SYSTEMTRAY_RESTORE    1001
#define IDC_SYSTEMTRAY_NEW        1002
#define IDC_SYSTEMTRAY_MONLY      1003
#define IDC_SYSTEMTRAY_FILTER     1004

#define IDC_CLEAR_PANE1           1010
#define IDC_CLEAR_PANE2           1011

#define IDC_STATHRF64N            1091
#define IDC_STATHRF64A            1092
#define IDC_STATHRF32N            1093
#define IDC_STATHRF32A            1094
#define IDC_STATHRF16N            1095
#define IDC_STATHRF16A            1096
#define IDC_STATHRP24N            1097
#define IDC_STATHRP24A            1098
#define IDC_STATHRP12N            1099
#define IDC_STATHRP12A            1100
#define IDC_STATHRP512N           1101
#define IDC_STATHRP512A           1102
#define IDC_STATHR_ACARS_N        1103
#define IDC_STATHR_ACARS_A        1104
#define IDC_STATHR_MB_N           1105
#define IDC_STATHR_MB_A           1106
#define IDC_STATHR_EM_N           1107
#define IDC_STATHR_EM_A           1108

#define IDC_STATDLF64N            1110
#define IDC_STATDLF64A            1111
#define IDC_STATDLF32N            1112
#define IDC_STATDLF32A            1113
#define IDC_STATDLF16N            1114
#define IDC_STATDLF16A            1115
#define IDC_STATDLP24N            1116
#define IDC_STATDLP24A            1117
#define IDC_STATDLP12N            1118
#define IDC_STATDLP12A            1119
#define IDC_STATDLP512N           1120
#define IDC_STATDLP512A           1121
#define IDC_STATDL_ACARS_N        1122
#define IDC_STATDL_ACARS_A        1123
#define IDC_STATDL_MB_N           1124
#define IDC_STATDL_MB_A           1125
#define IDC_STATDL_EM_N           1126
#define IDC_STATDL_EM_A           1127

#define IDC_STATFILEEN            1130
#define IDC_STATFILE              1131
#define IDC_STATFILEDATE          1132
#define IDC_STATBROWSE            1133

#define IDC_THRESHOLD512          1140
#define IDC_THRESHOLD1200         1141
#define IDC_THRESHOLD2400         1142
#define IDC_THRESHOLD1600         1143
#define IDC_RESYNC512             1144
#define IDC_RESYNC1200            1145
#define IDC_RESYNC2400            1146
#define IDC_RESYNC1600            1147
#define IDC_CENTERING512          1148
#define IDC_CENTERING1200         1149
#define IDC_CENTERING2400         1150
#define IDC_CENTERING1600         1151

#define IDC_WEBSITE               1160

#define IDC_DEBUG_OS              1170
#define IDC_DEBUG_STARTED         1171
#define IDC_DEBUG_RUNNING         1172
#define IDC_DEBUG_INPUT           1173
#define IDC_DEBUG_FLEXTIME        1174
#define IDC_DEBUG_MSG             1175
#define IDC_DEBUG_REJECTED        1176
#define IDC_DEBUG_BLOCKED         1177
#define IDC_DEBUG_BLOCKBUFFER     1178
#define IDC_DEBUG_MISSED          1179
#define IDC_DEBUG_GROUPMSG        1180
#define IDC_DEBUG_TEST            1181

#define IDW_TOOL_BAR              1200
#define IDW_STATUS_BAR            1218
#define IDT_TOOLBAR_BTN0          1201
#define IDT_TOOLBAR_BTN1          1202
#define IDT_TOOLBAR_BTN2          1203
#define IDT_TOOLBAR_BTN3          1204
#define IDT_TOOLBAR_BTN4          1205
#define IDT_TOOLBAR_BTN5          1206
#define IDT_TOOLBAR_BTN6          1207
#define IDT_TOOLBAR_BTN7          1208
#define IDT_TOOLBAR_BTN8          1209
#define IDT_TOOLBAR_BTN9          1210
#define IDT_TOOLBAR_BTN10         1211
#define IDT_TOOLBAR_BTN11         1212
#define IDT_TOOLBAR_BTN12         1213
#define IDT_TOOLBAR_BTN13         1214
#define IDT_TOOLBAR_BTN14         1215
#define IDT_TOOLBAR_BTN15         1216
#define IDT_TOOLBAR_BTN16         1217

#define IDC_SMTP                  1221
#define IDC_SMTP_SETTING          1222
#define IDC_SMTP_HOST             1223
#define IDC_SMTP_HELO             1224
#define IDC_SMTP_TO               1225
#define IDC_SMTP_FROM             1226
#define IDC_SMTP_TEST             1227
#define IDC_SMTP_RESPONSE         1228
#define IDC_SMTP_ADDRESS          1229
#define IDC_SMTP_TIME             1230
#define IDC_SMTP_DATE             1231
#define IDC_SMTP_MODE             1232
#define IDC_SMTP_TYPE             1233
#define IDC_SMTP_BITRATE          1234
#define IDC_SMTP_MESSAGE          1235
#define IDC_SMTP_LABEL            1236
#define IDC_SMTP_USER             1237
#define IDC_SMTP_PASSWORD         1238
#define IDC_SMTP_PORT             1239
#define IDC_SMTP_AUTH             1240
#define IDC_SMTP_SENDIN           1241
#define IDC_SMTP_CHARSET          1242
#define IDC_SMTP_SESSIONS         1243
#define IDC_SMTP_EMAILS           1244
#define IDC_SMTP_ERRORS           1245
#define IDC_SMTP_LASTERROR        1246
#define IDC_SMTP_SSL			  1247

#define IDC_FTP_ENABLED           1320
#define IDC_FTP_SERVER            1321
#define IDC_FTP_PORT              1322
#define IDC_FTP_USERNAME          1323
#define IDC_FTP_PASSWORD          1324
#define IDC_FTP_CLEAR_PASSWORD    1325
#define IDC_FTP_REMOTE_DIR        1326
#define IDC_FTP_PASSIVE           1327
#define IDC_FTP_FILES             1328
#define IDC_FTP_ADD_FILES         1329
#define IDC_FTP_REMOVE_FILES      1330
#define IDC_FTP_INTERVAL          1331
#define IDC_FTP_UPLOAD_NOW        1332
#define IDC_FTP_STATUS            1333
#define IDC_FTP_PROTOCOL          1334
#define IDC_FTP_SSH_HOST_KEY      1335
#define IDC_FTP_SECURITY_NOTICE   1336

#define IDC_APPRISE_ENABLED       1340
#define IDC_APPRISE_ENDPOINT      1341
#define IDC_APPRISE_DESTINATIONS  1342
#define IDC_APPRISE_USERNAME      1343
#define IDC_APPRISE_PASSWORD      1344
#define IDC_APPRISE_INCLUDE_MESSAGE 1345
#define IDC_APPRISE_TEST          1346
#define IDC_APPRISE_CLEAR         1347
#define IDC_APPRISE_STATUS        1348
#define IDC_APPRISE_VERSION       1349

#define SETTINGS_HUB_DLGBOX        850
#define IDC_SETTINGS_THEME        1350
#define IDC_SETTINGS_THEME_STATUS 1351
#define IDC_SETTINGS_COLORS       1352
#define IDC_SETTINGS_FONT         1353
#define IDC_SETTINGS_VIEW         1354
#define IDC_SETTINGS_TRAY         1355
#define IDC_SETTINGS_DECODER      1356
#define IDC_SETTINGS_GENERAL      1357
#define IDC_SETTINGS_INPUT        1358
#define IDC_SETTINGS_VOLUME       1359
#define IDC_SETTINGS_EMAIL        1360
#define IDC_SETTINGS_NOTIFY       1361
#define IDC_SETTINGS_TRANSFER     1362
#define IDC_SETTINGS_SCROLLBACK   1363
#define IDC_SETTINGS_START_WINDOWS 1364
#define IDC_SETTINGS_START_STATUS 1365
#define IDC_SETTINGS_SIGNAL_SOURCE 1366

#define IDC_SIGNAL_SOURCE          1370
#define IDC_RTL_HOST               1371
#define IDC_RTL_PORT               1372
#define IDC_RTL_FREQUENCY          1373
#define IDC_RTL_SAMPLE_RATE        1374
#define IDC_RTL_AUDIO_RATE         1375
#define IDC_RTL_AUTOMATIC_GAIN     1376
#define IDC_RTL_GAIN               1377
#define IDC_RTL_PPM                1378
#define IDC_RTL_DEVICE             1379
#define IDC_RTL_TEST               1380
#define IDC_RTL_STATUS             1381
#define IDC_SIGNAL_RECORD_PATH     1382
#define IDC_SIGNAL_RECORD_BROWSE   1383
#define IDC_SIGNAL_RECORD_START    1384
#define IDC_SIGNAL_RECORD_STOP     1385
#define IDC_SIGNAL_REPLAY_PATH     1386
#define IDC_SIGNAL_REPLAY_BROWSE   1387
#define IDC_SIGNAL_REPLAY_START    1388
#define IDC_SIGNAL_REPLAY_STOP     1389
#define IDC_SIGNAL_DIAGNOSTIC_STATUS 1390
#define IDC_RTL_RECEIVER_PACKAGE   1470
#define IDC_RTL_RECEIVER_ADD       1471
#define IDC_RTL_RECEIVER_FOLDER    1472
#define IDC_SIGNAL_WAVEFORM        1473
#define IDC_SIGNAL_QUALITY_HISTORY 1474
#define IDC_SIGNAL_METRICS         1475
#define IDC_SIGNAL_CALIBRATE       1476
#define IDC_RTL_BANDWIDTH          1477
#define IDC_RTL_SIGNAL_CONDITIONER 1590
#define IDC_SIGNAL_SPECTRUM        1478
#define IDC_SIGNAL_WATERFALL       1479
#define IDC_PUBLISH_ENABLE         1400
#define IDC_PUBLISH_ACK            1401
#define IDC_PUBLISH_FILTERED       1402
#define IDC_PUBLISH_ALL            1403
#define IDC_PUBLISH_STATIC         1404
#define IDC_PUBLISH_PATH           1405
#define IDC_PUBLISH_BROWSE         1406
#define IDC_PUBLISH_WEBHOOK        1407
#define IDC_PUBLISH_URL            1408
#define IDC_PUBLISH_BEARER         1409
#define IDC_PUBLISH_HMAC           1410
#define IDC_PUBLISH_ALIAS          1411
#define IDC_PUBLISH_MASK           1412
#define IDC_PUBLISH_MESSAGE        1413
#define IDC_PUBLISH_PAUSED         1414
#define IDC_PUBLISH_INTERVAL       1415
#define IDC_PUBLISH_TEST           1416
#define IDC_PUBLISH_STATUS         1417
#define IDC_PUBLISH_OPEN           1418
#define IDC_SETTINGS_PUBLISH       1419

#define IDC_OUTPUT_ENABLE          1420
#define IDC_OUTPUT_ACK             1421
#define IDC_OUTPUT_FILTERED        1422
#define IDC_OUTPUT_ALL             1423
#define IDC_OUTPUT_MASK            1424
#define IDC_OUTPUT_MESSAGE         1425
#define IDC_OUTPUT_ALIAS           1426
#define IDC_OUTPUT_TAB             1427
#define IDC_OUTPUT_STATUS          1428
#define IDC_OUTPUT_MQTT_PANEL      1430
#define IDC_OUTPUT_MQTT_ENABLE     1431
#define IDC_OUTPUT_MQTT_BROKER_LABEL 1432
#define IDC_OUTPUT_MQTT_BROKER     1433
#define IDC_OUTPUT_MQTT_TOPIC_LABEL 1434
#define IDC_OUTPUT_MQTT_TOPIC      1435
#define IDC_OUTPUT_MQTT_USER_LABEL 1436
#define IDC_OUTPUT_MQTT_USER       1437
#define IDC_OUTPUT_MQTT_PASSWORD_LABEL 1438
#define IDC_OUTPUT_MQTT_PASSWORD   1439
#define IDC_OUTPUT_MQTT_INSECURE   1440
#define IDC_OUTPUT_MQTT_TEST       1441
#define IDC_OUTPUT_MQTT_NOTE       1442
#define IDC_OUTPUT_SQLITE_PANEL    1443
#define IDC_OUTPUT_SQLITE_ENABLE   1444
#define IDC_OUTPUT_SQLITE_PATH_LABEL 1445
#define IDC_OUTPUT_SQLITE_PATH     1446
#define IDC_OUTPUT_SQLITE_BROWSE   1447
#define IDC_OUTPUT_SQLITE_TABLE_LABEL 1448
#define IDC_OUTPUT_SQLITE_TABLE    1449
#define IDC_OUTPUT_SQLITE_TEST     1450
#define IDC_OUTPUT_SQLITE_NOTE     1451
#define IDC_OUTPUT_MYSQL_PANEL     1452
#define IDC_OUTPUT_MYSQL_ENABLE    1453
#define IDC_OUTPUT_MYSQL_DSN_LABEL 1454
#define IDC_OUTPUT_MYSQL_DSN       1455
#define IDC_OUTPUT_MYSQL_USER_LABEL 1456
#define IDC_OUTPUT_MYSQL_USER      1457
#define IDC_OUTPUT_MYSQL_PASSWORD_LABEL 1458
#define IDC_OUTPUT_MYSQL_PASSWORD  1459
#define IDC_OUTPUT_MYSQL_TABLE_LABEL 1460
#define IDC_OUTPUT_MYSQL_TABLE     1461
#define IDC_OUTPUT_MYSQL_TEST      1462
#define IDC_OUTPUT_MYSQL_NOTE      1463
#define IDC_OUTPUT_TELNET_PANEL    1464
#define IDC_OUTPUT_TELNET_ENABLE   1465
#define IDC_OUTPUT_TELNET_BIND_LABEL 1466
#define IDC_OUTPUT_TELNET_BIND     1467
#define IDC_OUTPUT_TELNET_PORT_LABEL 1468
#define IDC_OUTPUT_TELNET_PORT     1469
#define IDC_OUTPUT_TELNET_REMOTE   1480
#define IDC_OUTPUT_TELNET_TEST     1481
#define IDC_OUTPUT_TELNET_NOTE     1482
#define IDC_OUTPUT_TOAST_PANEL     1483
#define IDC_OUTPUT_TOAST_ENABLE    1484
#define IDC_OUTPUT_TOAST_MESSAGE   1485
#define IDC_OUTPUT_TOAST_TEST      1486
#define IDC_OUTPUT_TOAST_NOTE      1487
#define IDC_OUTPUT_MQTT_CLEAR_PASSWORD 1488
#define IDC_OUTPUT_MYSQL_CLEAR_PASSWORD 1489
#define IDC_SETTINGS_DATA_OUTPUTS  1490
#define IDC_HEALTH_SUMMARY         1500
#define IDC_HEALTH_LIST            1501
#define IDC_HEALTH_HISTORY         1502
#define IDC_HEALTH_ALERTS          1503
#define IDC_HEALTH_THRESHOLD       1504
#define IDC_HEALTH_APPLY           1505
#define IDC_HEALTH_ACKNOWLEDGE     1506
#define IDC_HEALTH_REFRESH         1507
#define IDC_SETTINGS_OUTPUT_HEALTH 1508
#define IDC_OUTPUT_OPEN_HEALTH     1509
#define IDC_BACKUP_EXPORT          1510
#define IDC_BACKUP_RESTORE         1511
#define IDC_BACKUP_STATUS          1512
#define IDC_BACKUP_PASSWORD_INFO   1513
#define IDC_BACKUP_PASSWORD_LABEL  1514
#define IDC_BACKUP_PASSWORD        1515
#define IDC_BACKUP_CONFIRM_LABEL   1516
#define IDC_BACKUP_CONFIRM         1517

#define IDC_CAPCODE_SEARCH         1520
#define IDC_CAPCODE_LIST           1521
#define IDC_CAPCODE_PROTOCOL       1522
#define IDC_CAPCODE_ADDRESS        1523
#define IDC_CAPCODE_NAME           1524
#define IDC_CAPCODE_AGENCY         1525
#define IDC_CAPCODE_NOTES          1526
#define IDC_CAPCODE_ENABLED        1527
#define IDC_CAPCODE_COLOR          1528
#define IDC_CAPCODE_SAVE           1529
#define IDC_CAPCODE_NEW            1530
#define IDC_CAPCODE_DELETE         1531
#define IDC_CAPCODE_IMPORT         1532
#define IDC_CAPCODE_EXPORT         1533
#define IDC_CAPCODE_STATUS         1534
#define IDC_CAPCODE_FILTER_TYPE    1591
#define IDC_CAPCODE_FILTER_TEXT    1592
#define IDC_CAPCODE_FILTER_LABEL   1593
#define IDC_CAPCODE_MATCH_EXACT    1594
#define IDC_CAPCODE_SHOW_LABEL     1595
#define IDC_CAPCODE_REJECT         1596
#define IDC_CAPCODE_COMMAND        1597
#define IDC_CAPCODE_MONITOR_ONLY   1598
#define IDC_CAPCODE_EMAIL          1599
#define IDC_CAPCODE_HIT_COUNTER    1600
#define IDC_CAPCODE_HIT_RESET      1601
#define IDC_CAPCODE_SEP_ENABLE     1602
#define IDC_CAPCODE_SEP_FILE1      1603
#define IDC_CAPCODE_SEP_FILE2      1604
#define IDC_CAPCODE_SEP_FILE3      1605
#define IDC_CAPCODE_SEP_BROWSE     1606
#define IDC_CAPCODE_MULTIWORD_HELP 1607
#define IDC_CAPCODE_LABEL_COLOR    1608

#define IDC_HISTORY_ENABLE         1540
#define IDC_HISTORY_MESSAGE        1541
#define IDC_HISTORY_RETENTION      1542
#define IDC_HISTORY_PATH           1543
#define IDC_HISTORY_BROWSE         1544
#define IDC_HISTORY_SAVE_SETTINGS  1545
#define IDC_HISTORY_SEARCH         1546
#define IDC_HISTORY_PROTOCOL       1547
#define IDC_HISTORY_FILTERED       1548
#define IDC_HISTORY_REFRESH        1549
#define IDC_HISTORY_LIST           1550
#define IDC_HISTORY_PREVIOUS       1551
#define IDC_HISTORY_NEXT           1552
#define IDC_HISTORY_PAGE           1553
#define IDC_HISTORY_PURGE          1554
#define IDC_HISTORY_STATUS         1555
#define IDC_HISTORY_EXPORT         1556

#define IDC_DASHBOARD_ENABLE       1560
#define IDC_DASHBOARD_PORT         1561
#define IDC_DASHBOARD_SAVE         1562
#define IDC_DASHBOARD_OPEN         1563
#define IDC_DASHBOARD_STATUS       1564

#define IDC_MULTI_LIST             1570
#define IDC_MULTI_ENABLE           1571
#define IDC_MULTI_LABEL            1572
#define IDC_MULTI_SOURCE           1573
#define IDC_MULTI_HOST             1574
#define IDC_MULTI_PORT             1575
#define IDC_MULTI_DEVICE           1576
#define IDC_MULTI_FREQUENCY        1577
#define IDC_MULTI_SAVE             1578
#define IDC_MULTI_START            1579
#define IDC_MULTI_STOP             1580
#define IDC_MULTI_STATUS           1581

#define IDS_SIGIND                1250
#define IDS_EXCLAM                1251
#define IDS_ABOUTLOGO             1252

#define IDM_ENGLISH               1260  // Note there must be a gap of atleast 11
                                        // places before next ID begins. i.e. 1271.
                                        // 1260 to 1270 are in use.

#define IDT_MENU_COPY             1300
#define IDT_MENU_PASTE            1301
#define IDT_MENU_SORT_ADDRESS     1302
#define IDT_MENU_SORT_LABEL       1303
#define IDT_MENU_RESET            1304
#define IDT_MENU_SELECTALL        1305
#define IDT_FILTERCHECKDUPLICATE  1306

#define IDT_MENU_RESTORE          1310

// Visual Studio resource-editor defaults. These replace the obsolete
// standalone resrc1.h generated by Visual C++ 6.
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        1600
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1610
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
